name: hyperexecute_run
on: push
jobs:
  golangci:
    name: hyperexecute grid testing
    runs-on: macos-latest
    steps:
      # checkout the repo
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'check env var'
        run: env | sort

      - name: 'provide access to file'
        run: chmod +x ./hypertest-concierge_test

      - name: run test
        run: ./hypertest-concierge_test --user himanshur --key Z8NzB5b8eDvLWGPVwUaImrDMBH1eqazVEYvr7e8NwpAY84drYB --config yaml/mac/junit_hyperexecute_autosplit_sample.yaml --env stage